### ISSUE TITLE
Render loop is too aggressive

### ISSUE THREAD

**Issue by BlackCapCoder** [WaywardGame/waywardgame.github.io#1]
I recognize that this is common practice nowadays, but I really dislike how wayward is redrawing the screen 60 times per second: it makes my fans turn on, my keyboard go hot, and in Wayward's case it seems entirely unnecessary to me!

Wayward is a great coffee break game; it is the sort of game I might play on my laptop while on the train to work, or while waiting for a meeting, or whatever- but it is disqualified because I don't want to bother my peers with the blaring fan noise!

#### Things I've tired:

* The Power-save mode option: apparently 40 percent utilization of 4 cores, just to continuously render a static options menu, with the game minimized and off-screen- constitutes as "power saving".
* Editing `launch_options.json` in the install folder: `limitFps: 10` seemingly has no effect
* Setting 'game.interval' with the chromium dev tools, which is (hard-coded?) to `1000/60ms`. Lowering this has the side effect of slowing down the entire game.
* Hijacking the `requestAnimationFrame` function: `old = requestAnimationFrame; requestAnimationFrame = (cb) => { setTimeout (() => old(cb), 100); }`. This works, but make the game less responsive

#### What I would like:

Don't redraw unless you have to!

As far as I know there are no idle animations, and so the only reason to redraw is because user input triggered the character to move, or the map to zoom, or something.

**Comment by vaughnroyko** [comment]
Can you confirm this is still an issue when "Disable UI Effects" is enabled? You may have to wait a bit for the fans to quiet down after selecting it.

**Comment by BlackCapCoder** [comment]
Confirmed. With "Disable UI Effects" and "Low power", at the start screen the game is running at an acceptable 12% cpu, single core. In-game this jumps to 40-50% on all available cores.

Worth noting, I am running this on a laptop with an intel APU at 3200x1800.

**Comment by BlackCapCoder** [comment]
I am talking out of my ass here, but from fiddling with the console I imagine that your gameloop looks a little bit like this:

```javascript
(function renderLoop ()
{
  requestAnimationFrame (_ => {
    game.render ();
    if (!isAnimating) handleInput ();
    renderLoop  ();
  });
})();

(function animationLoop ()
{
  setTimeout (_ => {
    if (isAnimating) stepAnimation ();
    animationLoop ();
  }, game.interval);
})();
```

`animationLoop` is the thing that is responsible for animating the player between tiles when they move. It does not actually render the game. It indirectly affect input handling in that player movement is ignored while we are animating player movement. It is iterative: if we slow down `game.interval`  animations take longer, but our framerate stays constant.

`renderLoop` is the thing that actually draws the game. It is also responsible for handling user input, such that if we slow down renderLoop we risk losing key-presses between frames. We rely on `requestAnimationFrame` to synchronize rendering with the monitors refresh rate, and we redraw unconditionally, even if nothing has changed.


I suggest that:
* Input handling is decoupled from rendering (we don't want to lose user input, even if the game runs slow)
* Animation is coupled to rendering (animations are useless unless we draw them)
* Animations are calculated based on time since last frame, not in steps of constant size (they should take constant time regardless of framerate)
* Introduce a concept of invalidation: in the render loop, a new frame is rendered if and only if the previous frame has been invalidated. Animations invalidate until past their duration, and the final frame has to be drawn even if the animation is over.

**Comment by vaughnroyko** [comment]
Thanks for the feedback. We have made some significant improvements to rendering performance and decoupled input/simulation from our rendering loop among other changes. You'll be able to see everything coming up in beta 2.9 (or in the dev branch once we start pushing nightly changes there again).

**Comment by vaughnroyko** [comment]
These improvements have been implemented in the latest build.
